version: '3.4'

services:
  database:
    image: mysql:8.0.34
    container_name: mysqldb
    ports:
      - "3306:3306"
    expose: 
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: hw8vup5e
      MYSQL_USER: cash
      MYSQL_PASSWORD: hw8vup5e
      MYSQL_DATABASE: cashflow_db

  cashflow.api:
    image: ${DOCKER_REGISTRY-}cashflowapi
    container_name: cashflowapi
    build:
      context: .
      dockerfile: CashFlow.Api/Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
   db-volume: