version: '3.4'

services:
  database:
    image: mysql:8.0.34
    container_name: mysqldb
    ports:
      - "3306:3306"
    expose: 
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: hw8vup5e
      MYSQL_USER: cash
      MYSQL_PASSWORD: hw8vup5e
      MYSQL_DATABASE: cashflow_db

  cashflow.api:
    image: ${DOCKER_REGISTRY-}cashflowapi
    container_name: cashflowapi
    build:
      context: .
      dockerfile: CashFlow.Api/Dockerfile
    depends_on: 
      - database
    ports:
      - "8000:5000"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

  cashflow.report.api:
    image: ${DOCKER_REGISTRY-}cashflowreportapi
    container_name: cashflowreportapi
    build:
      context: .
      dockerfile: CashFlow.Report.Api/Dockerfile
    depends_on: 
      - database
    ports:
      - "8001:5001"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

  seq:
    image: datalust/seq:latest
    container_name: seq
    volumes:
      - datadrive:/data
    environment:
          - ACCEPT_EULA=Y
    restart: unless-stopped    
    ports:
      - 5341:80

volumes:
   db-volume:
   datadrive: 